name: melos_rack

repository:
  type: "github"
  origin: "https://github.com/coolosos/diagnostic"
  owner: "coolosos"
  name: "diagnostic"

packages:
  - diagnostic/*
  - flutter_diagnostic/**
  - diagnostic_tools/**

command:
  version:
    # Only allow versioning to happen on main branch.
    branch: main
    # Generate commit links in package changelogs.
    linkToCommits: true
    updateGitTagRefs: true
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

  bootstrap:
    runPubGetInParallel: false

scripts:
  pub_upgrade:
    run: melos exec -c 1 -- "flutter pub upgrade"

  format:
    run: dart format .
    description: Run `dart format .` in all packages.

  analyze:
    run: |
      melos exec -c 5 --ignore="*example*" -- \
        dart analyze --fatal-infos .
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  format_check:
    run: dart format --set-exit-if-changed .
    description: Run `dart format --set-exit-if-changed .` in all packages.
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test
      ignore:
        - "*example*"
  coverage: melos exec -- "\$MELOS_ROOT_PATH/scripts/coverage.sh"
  combine_coverage: melos exec -- "\$MELOS_ROOT_PATH/scripts/combine_coverage.sh"
