name: diagnostic
description: Diagnostic packages interfaces for generate different managers or tool for control. Usually create for firebase, sentry, CloudWatch...
version: 1.3.0

repository: https://github.com/coolosos/diagnostic
issue_tracker: https://github.com/coolosos/diagnostic/issues

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.30.0
  coolint: ^2.1.2
